version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      day: "wednesday"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      # ESM only packages we can't update since VS Code doesn't
      # support ESM yet
      - dependency-name: "got"
      # following dependencies dropped support for Node.js v16
      # which is the current runtime for VS Code extensions
      - dependency-name: "@octokit/rest"
      # it breaks wdio-vscode-service
      - dependency-name: "vscode-uri"
      # Deprecated
      - dependency-name: "@vercel/client"
      # VS Code
      - dependency-name: "@types/vscode"
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
      - dependency-name: "typescript"
        update-types:
          - version-update:semver-major
      - dependency-name: "@connectrpc/connect-node"
        update-types:
          - version-update:semver-major
      - dependency-name: "vitest"
        update-types:
          - version-update:semver-major
      - dependency-name: "@vitest/coverage-v8"
        update-types:
          - version-update:semver-major
    groups:
      patch-updates:
        patterns:
          - "typescript"
          - "@connectrpc/connect-node"
        update-types:
          - patch
      types-node:
        patterns:
          - "@types/node"
        update-types:
          - minor
          - patch
      aws-sdk:
        patterns:
          - "@aws-sdk/client-ec2"
          - "@aws-sdk/client-eks"
          - "@aws-sdk/credential-providers"
      e2e-tests:
        patterns:
          - "@wdio/cli"
          - "@wdio/local-runner"
          - "@wdio/mocha-framework"
          - "@wdio/spec-reporter"
          - "chromedriver"
          - "expect-webdriverio"
          - "wdio-vscode-service"
          - "webdriverio"
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: "/examples/k8s"
    schedule:
      interval: weekly
      time: "05:30"
      day: "wednesday"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
