name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📦 Install Dependencies
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🏗 Build Project
        run: npm run build:dev
      - name: 🧪 Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
          options: "-screen 0 1600x1200x24"
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            test/screenshots
            test/logs
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '300000'
