name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          echo -n 'nvm "$@" && echo $NVM_BIN >> $GITHUB_PATH' >>  ~/.nvm/nvm.sh
          sudo cp ~/.nvm/nvm.sh /usr/local/bin/nvm
          sudo chmod +x /usr/local/bin/nvm
      - uses: coactions/setup-xvfb@v1
        with:
          run: |
            npm i -g runme
            npx runme2 configureNPM setup build test
          working-directory: ${{ env.GITHUB_WORKSPACE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            tests/e2e/screenshots
            tests/e2e/logs
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '300000'
