name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: 🧪 Setup and Test with Runme
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            npm i -g runme
            npx runme run --filename=CONTRIBUTING.md configureNPM
            npx runme run --filename=CONTRIBUTING.md setup
            npx runme run --filename=CONTRIBUTING.md build
            npx runme run --filename=CONTRIBUTING.md test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🔼 Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            tests/e2e/screenshots
            tests/e2e/logs
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '300000'
