name: Test inputs

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Runme release version"
        required: true
        type: string
        default: latest
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: "Release Channel"
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: "Publish on Visual Studio Marketplace?"
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"
      publishOpenVSX:
        description: "Publish on Open VSX Registry?"
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"
      requiredReleaseNumber:
        description: "Mandatory release number"
        required: true
        type: number
      optionalReleaseNumber:
        description: "Optional release number"
        required: false
        type: number
        default: 0
      requiredBoolean:
        description: "Required boolean value"
        required: true
        type: boolean
      optionalBoolean:
        description: "Optional boolean value"
        required: false
        type: boolean
        default: false
      environmentExample:
        description: "Environment example"
        required: true
        type: environment
        default: stage

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: runme
    steps:
      - name: Print inputs
        run: |
          echo "${{ toJSON(github.event.inputs) }}"
