name: Tests
on:
  pull_request:
  push:
    branches:
      - main

# cancel old edit events being processed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DO_NOT_TRACK: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: Install xvfb
        run: sudo apt-get update -y && sudo apt-get install xvfb
      - name: 👷 Install Dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🧪 Setup and Test with Runme
        run: xvfb-run npx runme run configureNPM setup build test:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNME_TEST_TOKEN: ${{ secrets.RUNME_TEST_TOKEN }}
          RUNME_PROJECT: ${{ github.workspace }}
          SHELL: bash
          GITHUB_ACTOR: ${{ github.actor }}
      - name: 🔼 Upload Artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: |
            tests/e2e/screenshots
            tests/e2e/logs
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: "300000"
